{
    "name": "Tourism Management",
    "summary": "Tours and travels management",
    "author": "BizzAppDev",
    "license": "AGPL-3",
    "sequence": 2,
    "website": "https://github.com/PacktPublishing" "/Odoo-15-Development-Essentials",
    "version": "15.0.1.0.0",
    "depends": [
        "base","sale",'mail',
    ],
    "data": [
        "data/cron.xml",
        "data/mail_template.xml",
        "data/data.xml",
        "reports/tourist_report.xml",
        "wizard/update_tour_view.xml",
        "wizard/update_booking_accomodation.xml",
        "security/ir.model.access.csv",
        "security/security.xml",
        "views/tour.xml",
        "views/booking_accomodation.xml",
        "views/tour_view.xml",
        "views/tour_itenerary.xml",
        "views/information_line.xml",
        "views/tour_details.xml",
        "views/flight.xml",
        "views/customer_review.xml",
        "views/package_info.xml",
        "views/home.xml",
        "views/ticket_details.xml",
        "views/tour_description.xml",
        "views/tour_packages.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
    "licence": "LGPL-3",
}
