from . import student
from . import teacher
from . import student_appointment
from . import contact_us
from . import director
from . import result
from . import admission
from . import toppers
from . import alumni
from . import registration
from . import fees
from . import canteen
from . import home
from . import sale_order
from . import sale_order_line
from . import stock_move
from . import purchase_order
from . import mrp_production
from . import mrp_workorder
from . import account_move_line
from . import stock_picking
from . import project
from . import stock_rule
from . import account_move
from . import project_task

